# Generated by Django 2.2.4 on 2020-11-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='razão social')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome dono')),
                ('dt_criation', models.DateTimeField(auto_now_add=True)),
                ('CNPJ', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('business', models.CharField(blank=True, max_length=200, null=True, verbose_name='tipo de negocio')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, max_length=300, null=True, verbose_name='Complemento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='cadastro',
        ),
    ]
